### ISSUE TITLE
CiviCRM 5.60+ compatibility

### ISSUE THREAD

**Issue by pbatroff** [systopia/Contact-Update-Queue#48]
Fix Code to be compatible with CiviCRM 5.60: 

```
CRM/I3val/Logic.php:86:    $activity_data['status_id'] = CRM_Core_OptionGroup::getValue('activity_status', 'Scheduled', 'name');
CRM/I3val/CustomData.php:141:            $activity_type = CRM_Core_OptionGroup::getValue('activity_type', $activity_type, 'name');
```

- Update CustomData Helper to 0.10
- use legecayCode extension to replace call in Logic.php:86

**Comment by jofranz** [comment]
You could use CustomDataHelpers `CRM_Legacycode_OptionGroup::getValue` method here instead of legacycode

**Comment by jofranz** [comment]
This is fixed in _0.6-alpha1_
